### PR TITLE
[WIP] Plugins support

### LINKED ISSUE #12: Add support for plugins (import and parsers especially)
It's hard to add custom formats support right now. Consider adding plugin system for importers and parsers.

### LINKED ISSUE #13: Cleanup `Book` model
There are a lot of unnescessary fields that really doesn't matter for almost anyone.
Maybe there should be somthing like 'meta' fields. Some indexed key-value fields under `meta.` namespace, so it'll be searchable with query like `meta.language:ru`.
It can be placed under custom namespace tag in OPDS model (like `series` field in `FeedEntry`).
Fields like `Size`, `LibId`, `Del`, `Language`, `Keywords` can be placed there.

### PR DESCRIPTION
**Pull request by shemanaev**
Basic plugins support to extend custom file formats import.
This will fix #12.

- [x] ~~file formats parser API~~
- [x] ~~importers API~~
- [x] ~~rework `Book` model to support custom fields. Fixes #13.~~
- [x] ~~allow not only predefined genres~~

### CODE REVIEW

**Comment by shemanaev** [comment]
@gerritv here is initial plugin API. You probably want check out `DotOPDS.Plugin.BookProvider.Inpx` as example for your pdf importer.

**Comment by gerritv** [comment]
I will start using this on Monday, Thank you!

**Comment by gerritv** [comment]
Started on porting my pdf provider, first step was beginning documentation :-)
https://github.com/gerritv/DotOPDS/wiki, not complete and not verified by doing my implementation but a start.

**Comment by shemanaev** [comment]
There is more to come 😃 Many pieces reworked so it almost fit your need I assume. Plugins can now provide custom fields (as keywords in your case) and make available them in the search screen. I'm still unsure if I want to remove Genres (they are optional now by the way 😉) and make custom fields "browseable" (like Genres page). I didn't find good solution for that usecase in Lucene. Your [proposition](https://wiki.apache.org/lucene-java/LuceneFAQ#How_do_I_retrieve_all_the_values_of_a_particular_field_that_exists_within_an_index.2C_across_all_documents.3F) has no pagination support and I really don't want do that by hands 😄.

**Comment by gerritv** [comment]
Super, I will try to catch up :-)
Re:  Your proposition has no pagination support and I really don't want do that by hands 😄. The present Genre list on first page (Browse by Genre) has a very long list that is also not paginated? For my case/preference I would prefer to Browse only for Genres/Categories that actually exist. I am not a fan of clicking on a link only to find nothing there :-) :-) Once I catch up on your enhancements I will experiment a bit. (Also have to get Aldiko to fix their OPDS implementation, that will probably take a while.)

**Comment by shemanaev** [comment]
> Genre list on first page (Browse by Genre) has a very long list that is also not paginated?

Well, it's predefined and two-level. When you import 350k items library or couple multi-level Genres totally makes sense.

> I am not a fan of clicking on a link only to find nothing there :-) :-)

So am I. But again, on big libraries one-paged list of Genres will be too big and determining which of genres exists in tree-based Genres power consuming.

Maybe I could provide custom fields browsing on main screen. Without pagination ofc :)

**Comment by gerritv** [comment]
I ported my pdf scanner to a plugin, no problems. Now to investigate the other new features!
Thank you

**Comment by gerritv** [comment]
IndexField and Book extension working great. Thank you

**Comment by gerritv** [comment]
I added this to LucenIndexStorage to retrieve actual Genres:

``` C#
public List<string> GetGenres(out int count, string field)
        {
            int counter = 0;
            List<string> genres = new List<string>();

            IndexReader reader = IndexReader.Open(new SimpleFSDirectory(new DirectoryInfo(Settings.Instance.DatabaseIndex)), true);
            TermEnum terms = reader.Terms(new Term(field, ""));
            while (field.Equals(terms.Term.Field))
            {
                genres.Add(terms.Term.Text);
                counter++;
                terms.Next();
            }
            reader.Dispose();
            count = counter;
            return genres;
        }
```

**Pull request merged**
